



# Absolute path to this script. /home/user/bin/foo.sh
SCRIPT=$(readlink -f $0)
# Absolute path this script is in. /home/user/bin
SCRIPTPATH=`dirname $SCRIPT`
echo "Inicializando Funções bash em $SCRIPTPATH"
source $SCRIPTPATH/core/coreSBBash.sh
source $SCRIPTPATH/VARIAVEIS/SB_VARIAVEIS.sh

enviarProjeto(){
PASTA_PROJETOS=$1
PROJETO=$2
 	
	alerta2 "Sincronizando projeto (pull seguido de git add all + push) em "$PASTA_PROJETOS/$PROJETO
	cd $PASTA_PROJETOS/$PROJETO
	./sincronizaGit.sh
        git config credential.helper store

	
}



for PROJETO in "${!PROJETOS_COLETIVO_JAVA_CORE[@]}"; do
	NOME_PASTA_PROJETO=${PROJETOS_COLETIVO_JAVA_CORE[$PROJETO]}
	PASTA_PROJETOS=${PASTAS_COLETIVO_JAVA_FW[$NOME_PASTA_PROJETO]}
	enviarProjeto $PASTA_PROJETOS $PROJETO;
done
for PROJETO in "${!PROJETOS_COLETIVO_JAVA_DESENVOLVEDOR_PROJETO[@]}"; do
	NOME_PASTA_PROJETO=${PROJETOS_COLETIVO_JAVA_DESENVOLVEDOR_PROJETO[$PROJETO]}
	PASTA_PROJETOS=${PASTAS_COLETIVO_JAVA_FW[$NOME_PASTA_PROJETO]}
	enviarProjeto $PASTA_PROJETOS $PROJETO;
done

for PROJETO in "${!PROJETOS_COLETIVO_JAVA_DESENVOLVEDOR_PROJETO_ERP_COMPLETO[@]}"; do
	NOME_PASTA_PROJETO=${PROJETOS_COLETIVO_JAVA_DESENVOLVEDOR_PROJETO_ERP_COMPLETO[$PROJETO]}
	PASTA_PROJETOS=${PASTAS_COLETIVO_JAVA_FW[$NOME_PASTA_PROJETO]}
	enviarProjeto $PASTA_PROJETOS $PROJETO;
done

for PROJETO in "${!PROJETOS_COLETIVO_JAVA_DESENVOLVEDOR_FRAMEWORK[@]}"; do
	NOME_PASTA_PROJETO=${PROJETOS_COLETIVO_JAVA_DESENVOLVEDOR_FRAMEWORK[$PROJETO]}
	PASTA_PROJETOS=${PASTAS_COLETIVO_JAVA_FW[$NOME_PASTA_PROJETO]}
	enviarProjeto $PASTA_PROJETOS $PROJETO;
done

